// Navigation.pqm — nav-table helper + builders for OpenEHR.Contents.
//
// `Table.ToNavigationTable` is NOT built into Power Query M — every connector
// copies it from the docs: https://learn.microsoft.com/en-us/power-query/handling-navigation-tables

let
    Aql     = Extension.LoadFunction("Aql.pqm"),
    Paging  = Extension.LoadFunction("Paging.pqm"),
    Schema  = Extension.LoadFunction("Schema.pqm"),

    Table.ToNavigationTable = (
        table             as table,
        keyColumns        as list,
        nameColumn        as text,
        dataColumn        as text,
        itemKindColumn    as text,
        itemNameColumn    as text,
        isLeafColumn      as text
    ) as table =>
        let
            tableType    = Value.Type(table),
            newTableType = Type.AddTableKey(tableType, keyColumns, true) meta [
                NavigationTable.NameColumn     = nameColumn,
                NavigationTable.DataColumn     = dataColumn,
                NavigationTable.ItemKindColumn = itemKindColumn,
                Preview.DelayColumn            = itemNameColumn,
                NavigationTable.IsLeafColumn   = isLeafColumn
            ],
            navigationTable = Value.ReplaceType(table, newTableType)
        in
            navigationTable,

    // Build the top-level navigator shown after connecting.
    BuildRoot = (cdrBaseUrl as text, adHocFn as function) as table =>
        let
            objects = #table(
                {"Name",          "Key",      "Data",                              "ItemKind", "ItemName", "IsLeaf"},
                {
                    {"Ad-hoc AQL",     "aql",      adHocFn,                             "Function", "Function", true},
                    {"Stored Queries", "stored",   BuildStoredQueries(cdrBaseUrl),      "Folder",   "Folder",   false},
                    {"Templates",      "templates", BuildTemplatesTable(cdrBaseUrl),    "Table",    "Table",    true},
                    {"EHRs",           "ehrs",     BuildEhrsTable(cdrBaseUrl),          "Table",    "Table",    true}
                }
            )
        in
            Table.ToNavigationTable(objects, {"Key"}, "Name", "Data", "ItemKind", "ItemName", "IsLeaf"),

    BuildStoredQueries = (cdrBaseUrl as text) as table =>
        let
            response = Web.Contents(
                cdrBaseUrl,
                [
                    RelativePath         = "definition/query",
                    Headers              = [#"Accept" = "application/json"] & Aql[AuthHeader](),
                    ManualStatusHandling = {401, 403, 404, 500},
                    ExcludedFromCacheKey = {"Authorization"}
                ]
            ),
            parsed   = Json.Document(response),
            items    = if parsed is list then parsed else Record.FieldOrDefault(parsed, "items", {}),
            rows     = List.Transform(items, (q) =>
                let
                    qname   = Record.FieldOrDefault(q, "qualified_name", Record.FieldOrDefault(q, "name", "unknown")),
                    version = Record.FieldOrDefault(q, "version", null),
                    leafKey = if version <> null then qname & "/" & version else qname,
                    invoke  = () => RunStoredQuery(cdrBaseUrl, qname, version)
                in
                    {qname, leafKey, invoke, "Function", "Function", true}
            ),
            tbl = #table(
                {"Name", "Key", "Data", "ItemKind", "ItemName", "IsLeaf"},
                rows
            )
        in
            Table.ToNavigationTable(tbl, {"Key"}, "Name", "Data", "ItemKind", "ItemName", "IsLeaf"),

    RunStoredQuery = (cdrBaseUrl as text, qualifiedName as text, optional version as nullable text) as table =>
        let
            path     = if version <> null and version <> ""
                then "query/" & qualifiedName & "/" & version
                else "query/" & qualifiedName,
            response = Web.Contents(
                cdrBaseUrl,
                [
                    RelativePath         = path,
                    Headers              = [#"Accept" = "application/json"] & Aql[AuthHeader](),
                    ManualStatusHandling = {400, 401, 403, 404, 408, 500},
                    ExcludedFromCacheKey = {"Authorization"}
                ]
            ),
            buffered = Binary.Buffer(response),
            meta     = Value.Metadata(response),
            status   = meta[Response.Status],
            rs       = if status >= 200 and status < 300
                then Json.Document(buffered)
                else Aql[RaiseError](status, buffered, qualifiedName)
        in
            Schema[ResultSetToTable](rs, true),

    BuildTemplatesTable = (cdrBaseUrl as text) as table =>
        let
            response = Web.Contents(
                cdrBaseUrl,
                [
                    RelativePath         = "definition/template/adl1.4",
                    Headers              = [#"Accept" = "application/json"] & Aql[AuthHeader](),
                    ExcludedFromCacheKey = {"Authorization"}
                ]
            ),
            parsed  = Json.Document(response),
            items   = if parsed is list then parsed else Record.FieldOrDefault(parsed, "templates", {}),
            table0  = Table.FromList(items, Splitter.SplitByNothing(), {"Record"}, null, ExtraValues.Error),
            // Expand a couple of standard fields; tolerate missing ones.
            fields  = {"template_id", "concept", "archetype_id", "created_timestamp"},
            expanded = Table.ExpandRecordColumn(table0, "Record", fields, fields)
        in
            expanded,

    BuildEhrsTable = (cdrBaseUrl as text) as table =>
        let
            rs = Paging[GetAllRows](
                cdrBaseUrl,
                "SELECT e/ehr_id/value AS EhrId, e/ehr_status/subject/external_ref/id/value AS SubjectId FROM EHR e",
                null, 1000, null
            )
        in
            Schema[ResultSetToTable](rs, true)
in
    [
        #"Table.ToNavigationTable" = Table.ToNavigationTable,
        BuildRoot                  = BuildRoot,
        BuildStoredQueries         = BuildStoredQueries,
        RunStoredQuery             = RunStoredQuery,
        BuildTemplatesTable        = BuildTemplatesTable,
        BuildEhrsTable             = BuildEhrsTable
    ]
